[package]
name = "solana_airdrop"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-client = "1.7"
solana-program = "1.7"
solana-sdk = "1.7"
csv = "1.1"
spl-token = "3.0"